events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }

        location /hls/ {
            proxy_pass http://minio:9000/cdn-bucket/videos/;
            add_header Cache-Control "max-age=3600";
        }
    }
}
